model:
  name: CNN
  channels: [16, 32, 64]
  kernels: [5, 5, 5]
  stride: 2
  padding: valid
  widths: []
  pooling_positions: []
  pooling_layer: null
  conv_regularization_layer: null
  conv_activation_function:
    name: nn.ReLU
    parameters: []
  mlp_regularization_layer: null
  mlp_activation_function: null

training:
  loss: CrossEntropy
  lr_scheduler:
    metric: CrossEntropy
  early_stopping:
    metric: CrossEntropy
  glob:
    early_stopping:
      metric: CrossEntropy

attack:
  ignore_gradient_layers: []
  regularization: 0.1
